# CPSC 375 Classwork - Introduction to Python

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ProfAvery/cpsc375-classwork/blob/main/python.ipynb)

- *Manager*:
- *Recorder*:
- *Presenter*:
- *Timekeeper*:

*Note*: On Google Colab, run the following code cell to download the `cpsc375` module before trying to `import`:

In [6]:
!mkdir -p ./cpsc375 && wget --quiet --timestamping https://raw.githubusercontent.com/ProfAvery/cpsc375-classwork/refs/heads/main/cpsc375/__init__.py --output-document=./cpsc375/__init__.py

In [32]:
from cpsc375 import *

## Part 1 - Slides 21-23

Calculate the mean of values: 1, 2, 5

In [43]:
values = [1, 2, 5]
sum(values) / len(values)

2.6666666666666665

Calculate the magnitude of vector (1, 2, 5)

Magnitude = $\sqrt{1^2 + 2^2 + 5^2}$

In [44]:
vector = [1, 2, 5]
magnitude = (1**2 + 2**2 + 5**2) ** 0.5
magnitude

5.477225575051661

Normalize the vector

*Divide each component by the magnitude (and save to a new variable)*

In [45]:
normalized_vector = [x / magnitude for x in vector]
normalized_vector

[0.18257418583505536, 0.3651483716701107, 0.9128709291752769]

Calculate the magnitude of the normalized vector

In [46]:
normalized_magnitude = sum(x**2 for x in normalized_vector) ** 0.5
normalized_magnitude

1.0


Calculate the mean of 1st 100 numbers: 1, 2, …, 100

In [29]:
numbers = list(range(1, 106))
mean_of_numbers = sum(numbers) / len(numbers)
print(f"The mean of the first 100 numbers is: {mean_of_numbers}")

The mean of the first 100 numbers is: 53.0

## Part 2 - Slide 33

In [36]:
?iris_dataset
iris.Species = iris.Species.astype("category")

Show all rows where Species is "setosa"

In [47]:
iris[iris["Species"] == "setosa"]

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

Show all rows where Sepal.Length > 3.0 and Species is "setosa"

In [48]:
iris[(iris["Sepal.Length"] > 3.0) & (iris["Species"] == "setosa")]

    Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

What is the largest value of Sepal.Length?

In [49]:
iris["Sepal.Length"].max()

7.9

Which row contains this value?

In [50]:
iris[iris["Sepal.Length"] == iris["Sepal.Length"].max()]

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
131           7.9          3.8           6.4          2.0  virginica

What Species corresponds to this largest Sepal.Length?

In [51]:
iris.loc[iris["Sepal.Length"].idxmax(), "Species"]

'virginica'

## Part 3 - Slide 37

Consider the data airquality

- How many rows, columns, what are the variable names?

In [52]:
airquality.shape
airquality.columns

Index(['Ozone', 'Solar.R', 'Wind', 'Temp', 'Month', 'Day'], dtype='object')

Are there any NAs in column Ozone?
- How many NAs in column Ozone?
- Which rows have NAs in column Ozone?

True
37

In [53]:
airquality["Ozone"].isna().any()
airquality["Ozone"].isna().sum()
airquality[airquality["Ozone"].isna()]

     Ozone  Solar.R  Wind  Temp  Month  Day
4      NaN      NaN  14.3    56      5    5
9      NaN    194.0   8.6    69      5   10
24     NaN     66.0  16.6    57      5   25
25     NaN    266.0  14.9    58      5   26
26     NaN      NaN   8.0    57      5   27
31     NaN    286.0   8.6    78      6    1
32     NaN    287.0   9.7    74      6    2
33     NaN    242.0  16.1    67      6    3
34     NaN    186.0   9.2    84      6    4
35     NaN    220.0   8.6    85      6    5
36     NaN    264.0  14.3    79      6    6
38     NaN    273.0   6.9    87      6    8
41     NaN    259.0  10.9    93      6   11
42     NaN    250.0   9.2    92      6   12
44     NaN    332.0  13.8    80      6   14
45     NaN    322.0  11.5    79      6   15
51     NaN    150.0   6.3    77      6   21
52     NaN     59.0   1.7    76      6   22
53     NaN     91.0   4.6    76      6   23
54     NaN    250.0   6.3    76      6   24
55     NaN    135.0   8.0    75      6   25
56     NaN    127.0   8.0    78      6   26
57     NaN     47.0  10.3    73      6   27
58     NaN     98.0  11.5    80      6   28
59     NaN     31.0  14.9    77      6   29
60     NaN    138.0   8.0    83      6   30
64     NaN    101.0  10.9    84      7    4
71     NaN    139.0   8.6    82      7   11
74     NaN    291.0  14.9    91      7   14
82     NaN    258.0   9.7    81      7   22
83     NaN    295.0  11.5    82      7   23
101    NaN    222.0   8.6    92      8   10
102    NaN    137.0  11.5    86      8   11
106    NaN     64.0  11.5    79      8   15
114    NaN    255.0  12.6    75      8   23
118    NaN    153.0   5.7    88      8   27
149    NaN    145.0  13.2    77      9   27

What is the mean of the Ozone variable?

In [54]:
airquality["Ozone"].mean()

np.float64(42.12931034482759)